// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CCity
{
    public int CityId { get; set; }

    public string CityName { get; set; }

    public virtual ICollection<CVenue> CVenues { get; set; } = new List<CVenue>();
}