// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CCoachBooking
{
    public int CoachBookingId { get; set; }

    public int SlotId { get; set; }

    public int UserId { get; set; }

    public DateTime BookingTime { get; set; }

    public string Status { get; set; }

    public int FinalPrice { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CReview> CReviews { get; set; } = new List<CReview>();

    public virtual CCoachTimeSlot Slot { get; set; }

    public virtual UUser User { get; set; }
}