// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CCoachTimeSlot
{
    public int SlotId { get; set; }

    public int CoachScheduleId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public bool IsBooked { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CCoachBooking> CCoachBookings { get; set; } = new List<CCoachBooking>();

    public virtual CCoachSchedule CoachSchedule { get; set; }
}