// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CCoachSchedule
{
    public int CoachScheduleId { get; set; }

    public int CoachId { get; set; }

    public DateOnly WorkDate { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CCoachTimeSlot> CCoachTimeSlots { get; set; } = new List<CCoachTimeSlot>();

    public virtual UCoach Coach { get; set; }
}