// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CCourse
{
    public int CourseId { get; set; }

    public int CategoryId { get; set; }

    public string CourseName { get; set; }

    public string Courselevel { get; set; }

    public int Price { get; set; }

    public int Duration { get; set; }

    public int VenueId { get; set; }

    public int? CancelBeforeHours { get; set; }

    public string Description { get; set; }

    public string FImageUrl { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CCourseCategory Category { get; set; }

    public virtual CVenue Venue { get; set; }
}