// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CCourseSchedule
{
    public int ScheduleId { get; set; }

    public int CourseId { get; set; }

    public int CoachId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int MaxCapacity { get; set; }

    public int CurrentCapacity { get; set; }

    public DateTime? EnrollDeadline { get; set; }

    public string Status { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CCourseBooking> CCourseBookings { get; set; } = new List<CCourseBooking>();
}