// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CCourseBooking
{
    public int CourseBookingId { get; set; }

    public int ScheduleId { get; set; }

    public int UserId { get; set; }

    public DateTime BookingTime { get; set; }

    public string Status { get; set; }

    public int OriginalPrice { get; set; }

    public int? DiscountId { get; set; }

    public int DiscountAmount { get; set; }

    public int FinalPrice { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? PaidAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CReview> CReviews { get; set; } = new List<CReview>();

    public virtual CDiscount Discount { get; set; }

    public virtual CCourseSchedule Schedule { get; set; }

    public virtual UUser User { get; set; }
}