// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CDiscount
{
    public int DiscountId { get; set; }

    public string Code { get; set; }

    public string DiscountType { get; set; }

    public int DiscountValue { get; set; }

    public int MinSpend { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CCourseBooking> CCourseBookings { get; set; } = new List<CCourseBooking>();
}