// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CReviewTagMap
{
    public int RewiewtagmapId { get; set; }

    public int ReviewId { get; set; }

    public int TagId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual CReview Review { get; set; }

    public virtual CReviewTag Tag { get; set; }
}