// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CReview
{
    public int ReviewId { get; set; }

    public int UserId { get; set; }

    public int? CourseBookingId { get; set; }

    public int? CoachBookingId { get; set; }

    public int Rating { get; set; }

    public int? TeachingQuality { get; set; }

    public int? EnvironmentScore { get; set; }

    public int? DifficultyScore { get; set; }

    public int? ValueScore { get; set; }

    public string Comment { get; set; }

    public DateTime ReviewTime { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CReviewTagMap> CReviewTagMaps { get; set; } = new List<CReviewTagMap>();

    public virtual CCoachBooking CoachBooking { get; set; }

    public virtual CCourseBooking CourseBooking { get; set; }

    public virtual UUser User { get; set; }
}