// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class CVenue
{
    public int VenueId { get; set; }

    public string VenueName { get; set; }

    public string Address { get; set; }

    public int CityId { get; set; }

    public string Description { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CCourse> CCourses { get; set; } = new List<CCourse>();

    public virtual CCity City { get; set; }

    public virtual ICollection<TMealOrder> TMealOrders { get; set; } = new List<TMealOrder>();

    public virtual ICollection<UCoach> UCoaches { get; set; } = new List<UCoach>();
}