// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace gym_api.Models;
public partial class dbFitness2Context : DbContext // 這裡要改成你產出的類別名稱
{
    // 保留這個空建構子，方便某些開發場景使用
    public dbFitness2Context() { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            IConfiguration Config = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("appsettings.json")
                .Build();

            optionsBuilder.UseSqlServer(Config.GetConnectionString("Fitness2Connection"));
        }
    }
}
public partial class dbFitness2Context : DbContext
{
    public dbFitness2Context(DbContextOptions<dbFitness2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<CCity> CCities { get; set; }

    public virtual DbSet<CCoachBooking> CCoachBookings { get; set; }

    public virtual DbSet<CCoachSchedule> CCoachSchedules { get; set; }

    public virtual DbSet<CCoachTimeSlot> CCoachTimeSlots { get; set; }

    public virtual DbSet<CCourse> CCourses { get; set; }

    public virtual DbSet<CCourseBooking> CCourseBookings { get; set; }

    public virtual DbSet<CCourseCategory> CCourseCategories { get; set; }

    public virtual DbSet<CCourseSchedule> CCourseSchedules { get; set; }

    public virtual DbSet<CDiscount> CDiscounts { get; set; }

    public virtual DbSet<CReview> CReviews { get; set; }

    public virtual DbSet<CReviewTag> CReviewTags { get; set; }

    public virtual DbSet<CReviewTagMap> CReviewTagMaps { get; set; }

    public virtual DbSet<CVenue> CVenues { get; set; }

    public virtual DbSet<SCart> SCarts { get; set; }

    public virtual DbSet<SCategory> SCategories { get; set; }

    public virtual DbSet<SComment> SComments { get; set; }

    public virtual DbSet<SDiscount> SDiscounts { get; set; }

    public virtual DbSet<SImage> SImages { get; set; }

    public virtual DbSet<SOrder> SOrders { get; set; }

    public virtual DbSet<SOrderDetail> SOrderDetails { get; set; }

    public virtual DbSet<SPayment> SPayments { get; set; }

    public virtual DbSet<SProduct> SProducts { get; set; }

    public virtual DbSet<SShipper> SShippers { get; set; }

    public virtual DbSet<SSpecification> SSpecifications { get; set; }

    public virtual DbSet<SSupplier> SSuppliers { get; set; }

    public virtual DbSet<TMeal> TMeals { get; set; }

    public virtual DbSet<TMealCategory> TMealCategories { get; set; }

    public virtual DbSet<TMealEverydayMenu> TMealEverydayMenus { get; set; }

    public virtual DbSet<TMealFavoriteMeal> TMealFavoriteMeals { get; set; }

    public virtual DbSet<TMealOrder> TMealOrders { get; set; }

    public virtual DbSet<TMealOrderItem> TMealOrderItems { get; set; }

    public virtual DbSet<TMealPickUpTime> TMealPickUpTimes { get; set; }

    public virtual DbSet<UCoach> UCoaches { get; set; }

    public virtual DbSet<UCoachSkill> UCoachSkills { get; set; }

    public virtual DbSet<UCouchDeactivateLog> UCouchDeactivateLogs { get; set; }

    public virtual DbSet<UDairy> UDairies { get; set; }

    public virtual DbSet<UDairyDetail> UDairyDetails { get; set; }

    public virtual DbSet<UDietType> UDietTypes { get; set; }

    public virtual DbSet<UExerciseItem> UExerciseItems { get; set; }

    public virtual DbSet<UExerciseRecord> UExerciseRecords { get; set; }

    public virtual DbSet<UExerciseType> UExerciseTypes { get; set; }

    public virtual DbSet<UFood> UFoods { get; set; }

    public virtual DbSet<UFoodCategory> UFoodCategories { get; set; }

    public virtual DbSet<UUser> UUsers { get; set; }

    public virtual DbSet<UUserDeactivateLog> UUserDeactivateLogs { get; set; }

    public virtual DbSet<UUserHealthProfile> UUserHealthProfiles { get; set; }

    public virtual DbSet<UUserWeightRecord> UUserWeightRecords { get; set; }

    public virtual DbSet<YCustomerService> YCustomerServices { get; set; }

    public virtual DbSet<YFaq> YFaqs { get; set; }

    public virtual DbSet<YImage> YImages { get; set; }

    public virtual DbSet<YImageRelation> YImageRelations { get; set; }

    public virtual DbSet<YJoinForm> YJoinForms { get; set; }

    public virtual DbSet<YPost> YPosts { get; set; }

    public virtual DbSet<YPostCategory> YPostCategories { get; set; }

    public virtual DbSet<YPostEvent> YPostEvents { get; set; }

    public virtual DbSet<YPostLike> YPostLikes { get; set; }

    public virtual DbSet<YPostTagMapping> YPostTagMappings { get; set; }

    public virtual DbSet<YQuestionCategory> YQuestionCategories { get; set; }

    public virtual DbSet<YTag> YTags { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CCity>(entity =>
        {
            entity.HasKey(e => e.CityId);

            entity.ToTable("cCity");

            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.CityName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("cityName");
        });

        modelBuilder.Entity<CCoachBooking>(entity =>
        {
            entity.HasKey(e => e.CoachBookingId).HasName("PK__cCoachBo__8384E704BDE4287F");

            entity.ToTable("cCoachBookings");

            entity.Property(e => e.CoachBookingId).HasColumnName("coachBookingId");
            entity.Property(e => e.BookingTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__cCoachBoo__booki__6442E2C9")
                .HasColumnType("datetime")
                .HasColumnName("bookingTime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FinalPrice).HasColumnName("finalPrice");
            entity.Property(e => e.SlotId).HasColumnName("slotId");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Slot).WithMany(p => p.CCoachBookings)
                .HasForeignKey(d => d.SlotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CoachBookings_Slots");

            entity.HasOne(d => d.User).WithMany(p => p.CCoachBookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cCoachBookings_uUser");
        });

        modelBuilder.Entity<CCoachSchedule>(entity =>
        {
            entity.HasKey(e => e.CoachScheduleId).HasName("PK__cCoachSc__828F5DC6B4D4EBA8");

            entity.ToTable("cCoachSchedules");

            entity.Property(e => e.CoachScheduleId).HasColumnName("coachScheduleId");
            entity.Property(e => e.CoachId).HasColumnName("coachId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.WorkDate).HasColumnName("workDate");

            entity.HasOne(d => d.Coach).WithMany(p => p.CCoachSchedules)
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cCoachSchedules_uCoach");
        });

        modelBuilder.Entity<CCoachTimeSlot>(entity =>
        {
            entity.HasKey(e => e.SlotId).HasName("PK__cCoachTi__9C4A67132291DB3D");

            entity.ToTable("cCoachTimeSlots");

            entity.Property(e => e.SlotId).HasColumnName("slotId");
            entity.Property(e => e.CoachScheduleId).HasColumnName("coachScheduleId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("endTime");
            entity.Property(e => e.IsBooked).HasColumnName("isBooked");
            entity.Property(e => e.StartTime)
                .HasColumnType("datetime")
                .HasColumnName("startTime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.CoachSchedule).WithMany(p => p.CCoachTimeSlots)
                .HasForeignKey(d => d.CoachScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TimeSlots_Schedules");
        });

        modelBuilder.Entity<CCourse>(entity =>
        {
            entity.HasKey(e => e.CourseId).HasName("PK__cCourses__2AA84FD197F7D86D");

            entity.ToTable("cCourses");

            entity.Property(e => e.CourseId).HasColumnName("courseId");
            entity.Property(e => e.CancelBeforeHours).HasColumnName("cancelBeforeHours");
            entity.Property(e => e.CategoryId).HasColumnName("categoryId");
            entity.Property(e => e.CourseName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("courseName");
            entity.Property(e => e.Courselevel)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("courselevel");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.FImageUrl).HasColumnName("fImageUrl");
            entity.Property(e => e.Price).HasColumnName("price");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.VenueId).HasColumnName("venueId");

            entity.HasOne(d => d.Category).WithMany(p => p.CCourses)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cCourses_Category");

            entity.HasOne(d => d.Venue).WithMany(p => p.CCourses)
                .HasForeignKey(d => d.VenueId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cCourses_Venue");
        });

        modelBuilder.Entity<CCourseBooking>(entity =>
        {
            entity.HasKey(e => e.CourseBookingId).HasName("PK__cCourseB__454324B4017E9811");

            entity.ToTable("cCourseBookings");

            entity.Property(e => e.CourseBookingId).HasColumnName("courseBookingId");
            entity.Property(e => e.BookingTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("bookingTime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DiscountAmount).HasColumnName("discountAmount");
            entity.Property(e => e.DiscountId).HasColumnName("discountId");
            entity.Property(e => e.FinalPrice).HasColumnName("finalPrice");
            entity.Property(e => e.OriginalPrice).HasColumnName("originalPrice");
            entity.Property(e => e.PaidAt)
                .HasColumnType("datetime")
                .HasColumnName("paidAt");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("paymentMethod");
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("paymentStatus");
            entity.Property(e => e.ScheduleId).HasColumnName("scheduleId");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Discount).WithMany(p => p.CCourseBookings)
                .HasForeignKey(d => d.DiscountId)
                .HasConstraintName("FK_cCourseBookings_cDiscounts");

            entity.HasOne(d => d.Schedule).WithMany(p => p.CCourseBookings)
                .HasForeignKey(d => d.ScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CourseBookings_Schedules");

            entity.HasOne(d => d.User).WithMany(p => p.CCourseBookings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cCourseBookings_uUser");
        });

        modelBuilder.Entity<CCourseCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__cCourseC__23CAF1D877155351");

            entity.ToTable("cCourseCategory");

            entity.Property(e => e.CategoryId).HasColumnName("categoryId");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("categoryName");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<CCourseSchedule>(entity =>
        {
            entity.HasKey(e => e.ScheduleId).HasName("PK__cCourseS__A532EDD4F5B658D3");

            entity.ToTable("cCourseSchedules");

            entity.Property(e => e.ScheduleId).HasColumnName("scheduleId");
            entity.Property(e => e.CoachId).HasColumnName("coachId");
            entity.Property(e => e.CourseId).HasColumnName("courseId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrentCapacity).HasColumnName("currentCapacity");
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("endTime");
            entity.Property(e => e.EnrollDeadline)
                .HasColumnType("datetime")
                .HasColumnName("enrollDeadline");
            entity.Property(e => e.MaxCapacity).HasColumnName("maxCapacity");
            entity.Property(e => e.StartTime)
                .HasColumnType("datetime")
                .HasColumnName("startTime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<CDiscount>(entity =>
        {
            entity.HasKey(e => e.DiscountId).HasName("PK__cDiscoun__D2130A6643694D71");

            entity.ToTable("cDiscounts");

            entity.Property(e => e.DiscountId).HasColumnName("discountId");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("code");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DiscountType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("discountType");
            entity.Property(e => e.DiscountValue).HasColumnName("discountValue");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.MinSpend).HasColumnName("minSpend");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<CReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__cReviews__2ECD6E045DC64908");

            entity.ToTable("cReviews");

            entity.Property(e => e.ReviewId).HasColumnName("reviewId");
            entity.Property(e => e.CoachBookingId).HasColumnName("coachBookingId");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.CourseBookingId).HasColumnName("courseBookingId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DifficultyScore).HasColumnName("difficultyScore");
            entity.Property(e => e.EnvironmentScore).HasColumnName("environmentScore");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.ReviewTime)
                .HasColumnType("datetime")
                .HasColumnName("reviewTime");
            entity.Property(e => e.TeachingQuality).HasColumnName("teachingQuality");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("userId");
            entity.Property(e => e.ValueScore).HasColumnName("valueScore");

            entity.HasOne(d => d.CoachBooking).WithMany(p => p.CReviews)
                .HasForeignKey(d => d.CoachBookingId)
                .HasConstraintName("FK_cReviews_cCoachBookings");

            entity.HasOne(d => d.CourseBooking).WithMany(p => p.CReviews)
                .HasForeignKey(d => d.CourseBookingId)
                .HasConstraintName("FK_cReviews_cCourseBookings");

            entity.HasOne(d => d.User).WithMany(p => p.CReviews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cReviews_uUser");
        });

        modelBuilder.Entity<CReviewTag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("PK__cReviewT__50FC0157E35FE85C");

            entity.ToTable("cReviewTags");

            entity.Property(e => e.TagId).HasColumnName("tagId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("tagName");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<CReviewTagMap>(entity =>
        {
            entity.HasKey(e => e.RewiewtagmapId).HasName("PK__cReviewT__8A16032B562115C1");

            entity.ToTable("cReviewTagMap");

            entity.Property(e => e.RewiewtagmapId).HasColumnName("rewiewtagmapId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ReviewId).HasColumnName("reviewId");
            entity.Property(e => e.TagId).HasColumnName("tagId");

            entity.HasOne(d => d.Review).WithMany(p => p.CReviewTagMaps)
                .HasForeignKey(d => d.ReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cReviewTagMap_cReviews");

            entity.HasOne(d => d.Tag).WithMany(p => p.CReviewTagMaps)
                .HasForeignKey(d => d.TagId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cReviewTagMap_Tags");
        });

        modelBuilder.Entity<CVenue>(entity =>
        {
            entity.HasKey(e => e.VenueId).HasName("PK__cVenues__4DDFB6FF5428CF8B");

            entity.ToTable("cVenues");

            entity.Property(e => e.VenueId).HasColumnName("venueId");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasColumnName("address");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.VenueName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("venueName");

            entity.HasOne(d => d.City).WithMany(p => p.CVenues)
                .HasForeignKey(d => d.CityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cVenues_cCity");
        });

        modelBuilder.Entity<SCart>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__sCart__415B03B88E49461F");

            entity.ToTable("sCart");

            entity.Property(e => e.CartId).HasColumnName("cartId");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("price");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.SpecId).HasColumnName("specId");
            entity.Property(e => e.TimeStamp)
                .HasColumnType("datetime")
                .HasColumnName("timeStamp");

            entity.HasOne(d => d.Spec).WithMany(p => p.SCarts)
                .HasForeignKey(d => d.SpecId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sCart_sSpecification");

            entity.HasOne(d => d.User).WithMany(p => p.SCarts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sCart_uUser");
        });

        modelBuilder.Entity<SCategory>(entity =>
        {
            entity.HasKey(e => e.CId).HasName("PK__sCategor__D830D4777D770DD4");

            entity.ToTable("sCategory");

            entity.Property(e => e.CId).HasColumnName("cId");
            entity.Property(e => e.CName)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("cName");
        });

        modelBuilder.Entity<SComment>(entity =>
        {
            entity.HasKey(e => e.ComId).HasName("PK__sComment__9052B556C59F6B1C");

            entity.ToTable("sComment");

            entity.Property(e => e.ComId).HasColumnName("comId");
            entity.Property(e => e.CommentStar).HasColumnName("commentStar");
            entity.Property(e => e.CommentTime)
                .HasColumnType("datetime")
                .HasColumnName("commentTime");
            entity.Property(e => e.OdId).HasColumnName("odId");

            entity.HasOne(d => d.Od).WithMany(p => p.SComments)
                .HasForeignKey(d => d.OdId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sComment_sOrderDetail");
        });

        modelBuilder.Entity<SDiscount>(entity =>
        {
            entity.HasKey(e => e.DisId).HasName("PK__sDiscoun__71F24BB04C7D8F2C");

            entity.ToTable("sDiscount");

            entity.Property(e => e.DisId).HasColumnName("disId");
            entity.Property(e => e.Activate).HasColumnName("activate");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("code");
            entity.Property(e => e.Discount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("discount");
            entity.Property(e => e.DiscountType)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("discountType");
        });

        modelBuilder.Entity<SImage>(entity =>
        {
            entity.HasKey(e => e.PicId).HasName("PK__sImage__06707FED59ECF377");

            entity.ToTable("sImage");

            entity.Property(e => e.PicId).HasColumnName("picId");
            entity.Property(e => e.ImageType)
                .HasMaxLength(30)
                .HasColumnName("imageType");
            entity.Property(e => e.MainPicture).HasColumnName("mainPicture");
            entity.Property(e => e.PId).HasColumnName("pId");
            entity.Property(e => e.Picture).HasColumnName("picture");
            entity.Property(e => e.Sort).HasColumnName("sort");
            entity.Property(e => e.SpecId).HasColumnName("specId");

            entity.HasOne(d => d.PIdNavigation).WithMany(p => p.SImages)
                .HasForeignKey(d => d.PId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sImage_sProduct");

            entity.HasOne(d => d.Spec).WithMany(p => p.SImages)
                .HasForeignKey(d => d.SpecId)
                .HasConstraintName("FK_sImage_sSpecification");
        });

        modelBuilder.Entity<SOrder>(entity =>
        {
            entity.HasKey(e => e.OId).HasName("PK__sOrder__C2FECB3B4BBF9DFA");

            entity.ToTable("sOrder");

            entity.Property(e => e.OId).HasColumnName("oId");
            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.DisId).HasColumnName("disId");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.HandlingFee)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("handlingFee");
            entity.Property(e => e.MAddress)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("mAddress");
            entity.Property(e => e.MName)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("mName");
            entity.Property(e => e.MPhone)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("mPhone");
            entity.Property(e => e.Note).HasMaxLength(30);
            entity.Property(e => e.OStatus)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("oStatus");
            entity.Property(e => e.OrderNumber)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("orderNumber");
            entity.Property(e => e.PayId).HasColumnName("payId");
            entity.Property(e => e.PayStatus)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("payStatus");
            entity.Property(e => e.ShipFee)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("shipFee");
            entity.Property(e => e.ShipId).HasColumnName("shipId");
            entity.Property(e => e.Total)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("total");

            entity.HasOne(d => d.Dis).WithMany(p => p.SOrders)
                .HasForeignKey(d => d.DisId)
                .HasConstraintName("FK_sOrder_sDiscount");

            entity.HasOne(d => d.Pay).WithMany(p => p.SOrders)
                .HasForeignKey(d => d.PayId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sOrder_sPayment");

            entity.HasOne(d => d.Ship).WithMany(p => p.SOrders)
                .HasForeignKey(d => d.ShipId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sOrder_sShipper");

            entity.HasOne(d => d.User).WithMany(p => p.SOrders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sOrder_uUser");
        });

        modelBuilder.Entity<SOrderDetail>(entity =>
        {
            entity.HasKey(e => e.OdId).HasName("PK__sOrderDe__8D163A115F373317");

            entity.ToTable("sOrderDetail");

            entity.Property(e => e.OdId).HasColumnName("odId");
            entity.Property(e => e.OId).HasColumnName("oId");
            entity.Property(e => e.PName)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("pName");
            entity.Property(e => e.Quantity)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("quantity");
            entity.Property(e => e.SPrice)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("sPrice");
            entity.Property(e => e.SpecId).HasColumnName("specId");
            entity.Property(e => e.Subtotal).HasColumnType("decimal(10, 0)");

            entity.HasOne(d => d.OIdNavigation).WithMany(p => p.SOrderDetails)
                .HasForeignKey(d => d.OId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sOrderDetail_sOrder");

            entity.HasOne(d => d.Spec).WithMany(p => p.SOrderDetails)
                .HasForeignKey(d => d.SpecId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sOrderDetail_sSpecification");
        });

        modelBuilder.Entity<SPayment>(entity =>
        {
            entity.HasKey(e => e.PayId).HasName("PK__sPayment__082E8AC3644698E5");

            entity.ToTable("sPayment");

            entity.Property(e => e.PayId).HasColumnName("payId");
            entity.Property(e => e.Activate).HasColumnName("activate");
            entity.Property(e => e.HandlingFee)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("handlingFee");
            entity.Property(e => e.Payment)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<SProduct>(entity =>
        {
            entity.HasKey(e => e.PId).HasName("PK__sProduct__DD37D91AB471D02F");

            entity.ToTable("sProduct");

            entity.Property(e => e.PId).HasColumnName("pId");
            entity.Property(e => e.CId).HasColumnName("cId");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.PName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("pName");
            entity.Property(e => e.SupId).HasColumnName("supId");

            entity.HasOne(d => d.CIdNavigation).WithMany(p => p.SProducts)
                .HasForeignKey(d => d.CId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sProduct_sCategory");

            entity.HasOne(d => d.Sup).WithMany(p => p.SProducts)
                .HasForeignKey(d => d.SupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sProduct_sSupplier");
        });

        modelBuilder.Entity<SShipper>(entity =>
        {
            entity.HasKey(e => e.ShipId).HasName("PK__sShipper__CC873BC5CB3632F8");

            entity.ToTable("sShipper");

            entity.Property(e => e.ShipId).HasColumnName("shipId");
            entity.Property(e => e.FreeShipping)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("freeShipping");
            entity.Property(e => e.ShipFee)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("shipFee");
            entity.Property(e => e.Shipping)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<SSpecification>(entity =>
        {
            entity.HasKey(e => e.SpecId).HasName("PK__sSpecifi__DDDED96E616A0D27");

            entity.ToTable("sSpecification");

            entity.Property(e => e.SpecId).HasColumnName("specId");
            entity.Property(e => e.DiscountPrice)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("discountPrice");
            entity.Property(e => e.InStock)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("inStock");
            entity.Property(e => e.PId).HasColumnName("pId");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(10, 0)")
                .HasColumnName("price");
            entity.Property(e => e.Release).HasColumnName("release");
            entity.Property(e => e.SpecDetail).HasColumnName("specDetail");
            entity.Property(e => e.SpecName)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("specName");

            entity.HasOne(d => d.PIdNavigation).WithMany(p => p.SSpecifications)
                .HasForeignKey(d => d.PId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_sSpecification_sProduct");
        });

        modelBuilder.Entity<SSupplier>(entity =>
        {
            entity.HasKey(e => e.SupId).HasName("PK__sSupplie__DDDFDD36D7817754");

            entity.ToTable("sSupplier");

            entity.Property(e => e.SupId).HasColumnName("supId");
            entity.Property(e => e.SupName)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("supName");
        });

        modelBuilder.Entity<TMeal>(entity =>
        {
            entity.HasKey(e => e.FMealId).HasName("PK__tMeal__3564628F44CDC5EF");

            entity.ToTable("tMeal");

            entity.Property(e => e.FMealId).HasColumnName("fMealId");
            entity.Property(e => e.FCalories).HasColumnName("fCalories");
            entity.Property(e => e.FCarbs).HasColumnName("fCarbs");
            entity.Property(e => e.FCategoryId).HasColumnName("fCategoryId");
            entity.Property(e => e.FDescription)
                .HasMaxLength(300)
                .HasColumnName("fDescription");
            entity.Property(e => e.FFat).HasColumnName("fFat");
            entity.Property(e => e.FImageUrl).HasColumnName("fImageUrl");
            entity.Property(e => e.FIsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tMeal__fIsActive__44FF419A")
                .HasColumnName("fIsActive");
            entity.Property(e => e.FMealName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fMealName");
            entity.Property(e => e.FPrice).HasColumnName("fPrice");
            entity.Property(e => e.FProtein).HasColumnName("fProtein");

            entity.HasOne(d => d.FCategory).WithMany(p => p.TMeals)
                .HasForeignKey(d => d.FCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tMeal__fCategory__45F365D3");
        });

        modelBuilder.Entity<TMealCategory>(entity =>
        {
            entity.HasKey(e => e.FCategoryId).HasName("PK__tMealCat__53E607B3B4271167");

            entity.ToTable("tMealCategory");

            entity.Property(e => e.FCategoryId).HasColumnName("fCategoryId");
            entity.Property(e => e.FCategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("fCategoryName");
            entity.Property(e => e.FDescription)
                .HasMaxLength(300)
                .HasColumnName("fDescription");
            entity.Property(e => e.FIsActive)
                .HasDefaultValue(true)
                .HasColumnName("fIsActive");
        });

        modelBuilder.Entity<TMealEverydayMenu>(entity =>
        {
            entity.HasKey(e => e.FEverydayMenuId).HasName("PK__tMealEve__BD1D3B6C56681AFE");

            entity.ToTable("tMealEverydayMenu");

            entity.Property(e => e.FEverydayMenuId).HasColumnName("fEverydayMenuId");
            entity.Property(e => e.FIsActive)
                .HasDefaultValue(true)
                .HasColumnName("fIsActive");
            entity.Property(e => e.FMealId).HasColumnName("fMealId");
            entity.Property(e => e.FMenuDate).HasColumnName("fMenuDate");

            entity.HasOne(d => d.FMeal).WithMany(p => p.TMealEverydayMenus)
                .HasForeignKey(d => d.FMealId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tMealEver__fMeal__49C3F6B7");
        });

        modelBuilder.Entity<TMealFavoriteMeal>(entity =>
        {
            entity.HasKey(e => e.FFavoriteMealId).HasName("PK__tMealFav__DC1A45D8B4E10BCD");

            entity.ToTable("tMealFavoriteMeal");

            entity.Property(e => e.FFavoriteMealId).HasColumnName("fFavoriteMealID");
            entity.Property(e => e.FCreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fCreatedAt");
            entity.Property(e => e.FMealId).HasColumnName("fMealID");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FMeal).WithMany(p => p.TMealFavoriteMeals)
                .HasForeignKey(d => d.FMealId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tMealFavo__fMeal__6477ECF3");

            entity.HasOne(d => d.FUser).WithMany(p => p.TMealFavoriteMeals)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tMealFavoriteMeal_uUser");
        });

        modelBuilder.Entity<TMealOrder>(entity =>
        {
            entity.HasKey(e => e.FOrderId).HasName("PK__tMealOrd__5DA911DAF1183F45");

            entity.ToTable("tMealOrder");

            entity.Property(e => e.FOrderId).HasColumnName("fOrderId");
            entity.Property(e => e.FCartCreateAt)
                .HasColumnType("datetime")
                .HasColumnName("fCartCreateAt");
            entity.Property(e => e.FOrderAt)
                .HasColumnType("datetime")
                .HasColumnName("fOrderAt");
            entity.Property(e => e.FOrderEmail)
                .HasMaxLength(200)
                .HasColumnName("fOrderEmail");
            entity.Property(e => e.FOrderName)
                .HasMaxLength(100)
                .HasColumnName("fOrderName");
            entity.Property(e => e.FOrderPhone)
                .HasMaxLength(50)
                .HasColumnName("fOrderPhone");
            entity.Property(e => e.FOrderStatus)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fOrderStatus");
            entity.Property(e => e.FPayMethod)
                .HasMaxLength(30)
                .HasColumnName("fPayMethod");
            entity.Property(e => e.FTotalAmount).HasColumnName("fTotalAmount");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");
            entity.Property(e => e.FVenueId).HasColumnName("fVenueId");

            entity.HasOne(d => d.FUser).WithMany(p => p.TMealOrders)
                .HasForeignKey(d => d.FUserId)
                .HasConstraintName("FK_tMealOrder_uUser");

            entity.HasOne(d => d.FVenue).WithMany(p => p.TMealOrders)
                .HasForeignKey(d => d.FVenueId)
                .HasConstraintName("FK_tMealOrder_cVenues");
        });

        modelBuilder.Entity<TMealOrderItem>(entity =>
        {
            entity.HasKey(e => e.FOrderItemId).HasName("PK__tMealOrd__B8C28BFBF1F55345");

            entity.ToTable("tMealOrderItem");

            entity.Property(e => e.FOrderItemId).HasColumnName("fOrderItemId");
            entity.Property(e => e.FMealId).HasColumnName("fMealId");
            entity.Property(e => e.FOrderId).HasColumnName("fOrderId");
            entity.Property(e => e.FPickDate).HasColumnName("fPickDate");
            entity.Property(e => e.FPickTimeId).HasColumnName("fPickTimeID");
            entity.Property(e => e.FPickupStatus).HasColumnName("fPickupStatus");
            entity.Property(e => e.FQrContent).HasColumnName("fQrContent");
            entity.Property(e => e.FQty).HasColumnName("fQty");
            entity.Property(e => e.FSubtotal).HasColumnName("fSubtotal");
            entity.Property(e => e.FUnitPrice).HasColumnName("fUnitPrice");

            entity.HasOne(d => d.FMeal).WithMany(p => p.TMealOrderItems)
                .HasForeignKey(d => d.FMealId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tMealOrde__fMeal__5FB337D6");

            entity.HasOne(d => d.FOrder).WithMany(p => p.TMealOrderItems)
                .HasForeignKey(d => d.FOrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tMealOrde__fOrde__5EBF139D");

            entity.HasOne(d => d.FPickTime).WithMany(p => p.TMealOrderItems)
                .HasForeignKey(d => d.FPickTimeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tMealOrde__fPick__60A75C0F");
        });

        modelBuilder.Entity<TMealPickUpTime>(entity =>
        {
            entity.HasKey(e => e.FPickUpTimeId).HasName("PK__tMealPic__0C066B76F06FB9AB");

            entity.ToTable("tMealPickUpTime");

            entity.Property(e => e.FPickUpTimeId).HasColumnName("fPickUpTimeID");
            entity.Property(e => e.FEndTime)
                .HasPrecision(0)
                .HasColumnName("fEndTime");
            entity.Property(e => e.FIsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tMealPick__fIsAc__4222D4EF")
                .HasColumnName("fIsActive");
            entity.Property(e => e.FStartTime)
                .HasPrecision(0)
                .HasColumnName("fStartTime");
        });

        modelBuilder.Entity<UCoach>(entity =>
        {
            entity.HasKey(e => e.CoachId).HasName("PK__uCoach__F411D9412584E1A1");

            entity.ToTable("uCoach");

            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Descrition)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.HourlyRate)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("hourlyRate");
            entity.Property(e => e.Image)
                .HasColumnType("image")
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.VenueId).HasColumnName("venueId");

            entity.HasOne(d => d.Venue).WithMany(p => p.UCoaches)
                .HasForeignKey(d => d.VenueId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uCoach_cVenues");
        });

        modelBuilder.Entity<UCoachSkill>(entity =>
        {
            entity.HasKey(e => e.CoachSkillId).HasName("PK__uCoachSk__A7269B58E4CB23FE");

            entity.ToTable("uCoachSkill");

            entity.Property(e => e.SkillInfo)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.SkillName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Coach).WithMany(p => p.UCoachSkills)
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uCoachSkill_uCoach");
        });

        modelBuilder.Entity<UCouchDeactivateLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__uCouchDe__5E5486486340E544");

            entity.ToTable("uCouchDeactivateLog");

            entity.Property(e => e.DeactivateEndTime).HasColumnType("datetime");
            entity.Property(e => e.DeactivateStartTime).HasColumnType("datetime");
            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Coach).WithMany(p => p.UCouchDeactivateLogs)
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uCouchDeactivateLog_uCoach");
        });

        modelBuilder.Entity<UDairy>(entity =>
        {
            entity.HasKey(e => e.DairyId).HasName("PK__uDairy__47A894BFCD7749B2");

            entity.ToTable("uDairy");

            entity.Property(e => e.Description).HasMaxLength(100);

            entity.HasOne(d => d.User).WithMany(p => p.UDairies)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uDairy_uUser");
        });

        modelBuilder.Entity<UDairyDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__uDiaryDe__135C316D1F5A60D5");

            entity.ToTable("uDairyDetail");

            entity.Property(e => e.Kcal).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.Qty).HasColumnType("decimal(5, 1)");

            entity.HasOne(d => d.Dairy).WithMany(p => p.UDairyDetails)
                .HasForeignKey(d => d.DairyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Detail_Dairy");

            entity.HasOne(d => d.Food).WithMany(p => p.UDairyDetails)
                .HasForeignKey(d => d.FoodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Detail_Food");
        });

        modelBuilder.Entity<UDietType>(entity =>
        {
            entity.HasKey(e => e.DietTypeId).HasName("PK__uDietTyp__B578CC5F0ECEC3F3");

            entity.ToTable("uDietType");

            entity.Property(e => e.DietName)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.User).WithMany(p => p.UDietTypes)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_uDietType_uUser");
        });

        modelBuilder.Entity<UExerciseItem>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__uExercis__727E838BB395E96D");

            entity.ToTable("uExerciseItem");

            entity.Property(e => e.ExerciseName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.ExerciseType).WithMany(p => p.UExerciseItems)
                .HasForeignKey(d => d.ExerciseTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uExerciseItem_uExerciseType");
        });

        modelBuilder.Entity<UExerciseRecord>(entity =>
        {
            entity.HasKey(e => e.ExerciseId).HasName("PK__uExercis__A074AD2FAAA7620B");

            entity.ToTable("uExerciseRecord");

            entity.Property(e => e.Duration).HasColumnType("decimal(10, 1)");
            entity.Property(e => e.Kcal)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__uExerciseR__kcal__00200768")
                .HasColumnType("decimal(5, 1)");
            entity.Property(e => e.Machine).HasColumnName("machine");
            entity.Property(e => e.Met)
                .HasColumnType("decimal(5, 1)")
                .HasColumnName("MET");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 1)");

            entity.HasOne(d => d.Item).WithMany(p => p.UExerciseRecords)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uExerciseRecord_uExerciseItem");

            entity.HasOne(d => d.User).WithMany(p => p.UExerciseRecords)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uExerciseRecord_uUser");
        });

        modelBuilder.Entity<UExerciseType>(entity =>
        {
            entity.HasKey(e => e.ExerciseTypeId).HasName("PK__uExercis__6CBFB0B7556A6DF8");

            entity.ToTable("uExerciseType");

            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<UFood>(entity =>
        {
            entity.HasKey(e => e.FoodId).HasName("PK__uFood__856DB3EB68C99834");

            entity.ToTable("uFood");

            entity.Property(e => e.Cho)
                .HasColumnType("decimal(5, 1)")
                .HasColumnName("CHO");
            entity.Property(e => e.Fat).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.FoodImage).HasColumnType("image");
            entity.Property(e => e.FoodName)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Kcal).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.PortionSize).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.Protein).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.Text).HasMaxLength(50);

            entity.HasOne(d => d.Category).WithMany(p => p.UFoods)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uFood_Category");
        });

        modelBuilder.Entity<UFoodCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__uFoodCat__19093A0BB146B17C");

            entity.ToTable("uFoodCategory");

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<UUser>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__uUser__1788CC4CEC408B38");

            entity.ToTable("uUser");

            entity.HasIndex(e => e.Email, "UQ_User_Email").IsUnique();

            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__uUser__CreatedDa__6B24EA82")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.EmailVerifiedAt)
                .HasColumnType("datetime")
                .HasColumnName("email_verified_at");
            entity.Property(e => e.GoogleId).HasMaxLength(100);
            entity.Property(e => e.IsEmailVerified).HasAnnotation("Relational:DefaultConstraintName", "DF__uUser__IsEmailVe__70FDBF69");
            entity.Property(e => e.LineId).HasMaxLength(100);
            entity.Property(e => e.LoginProvider)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Local")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__uUser__LoginProv__71F1E3A2");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PasswordSalt).HasMaxLength(128);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Sex)
                .IsRequired()
                .HasMaxLength(5);
        });

        modelBuilder.Entity<UUserDeactivateLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__uUserDea__5E54864808D46895");

            entity.ToTable("uUserDeactivateLog");

            entity.Property(e => e.DeactivateEndTime).HasColumnType("datetime");
            entity.Property(e => e.DeactivateStartTime).HasColumnType("datetime");
            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.User).WithMany(p => p.UUserDeactivateLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_uUserDeactivateLog_uUser");
        });

        modelBuilder.Entity<UUserHealthProfile>(entity =>
        {
            entity.HasKey(e => e.HealthProfileId).HasName("PK__uUserHea__73C2C2D595EA79B6");

            entity.ToTable("uUserHealthProfile");

            entity.Property(e => e.Bmi)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("BMI");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Goal).HasMaxLength(100);
            entity.Property(e => e.Height).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.MedicalNote).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.User).WithMany(p => p.UUserHealthProfiles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserHealthProfile_User");
        });

        modelBuilder.Entity<UUserWeightRecord>(entity =>
        {
            entity.HasKey(e => e.RecordId).HasName("PK__uUserWei__FBDF78E91E609A7E");

            entity.ToTable("uUserWeightRecord");

            entity.Property(e => e.BodyFat).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.MuscleMass).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.User).WithMany(p => p.UUserWeightRecords)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserWeightRecord_User");
        });

        modelBuilder.Entity<YCustomerService>(entity =>
        {
            entity.HasKey(e => e.CustomerServiceId).HasName("PK__yCustome__1FBD44D014B9172C");

            entity.ToTable("yCustomerService");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__yCustomer__Creat__2610A626")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Image).HasColumnType("image");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF__yCustomer__IsDel__2704CA5F");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RepliedAt).HasColumnType("datetime");
            entity.Property(e => e.Status).HasAnnotation("Relational:DefaultConstraintName", "DF__yCustomer__Statu__251C81ED");

            entity.HasOne(d => d.Coach).WithMany(p => p.YCustomerServices)
                .HasForeignKey(d => d.CoachId)
                .HasConstraintName("FK_yCustomerService_uCoach");

            entity.HasOne(d => d.QuestionCategory).WithMany(p => p.YCustomerServices)
                .HasForeignKey(d => d.QuestionCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yCustomerService_yQuestionCategory");

            entity.HasOne(d => d.User).WithMany(p => p.YCustomerServices)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_yCustomerService_uUser");
        });

        modelBuilder.Entity<YFaq>(entity =>
        {
            entity.HasKey(e => e.FaqId).HasName("PK__yFAQ__9C741C43F9B61BC0");

            entity.ToTable("yFAQ");

            entity.Property(e => e.Answer).IsRequired();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Question).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.QuestionCategory).WithMany(p => p.YFaqs)
                .HasForeignKey(d => d.QuestionCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yFAQ_yQuestionCategory");
        });

        modelBuilder.Entity<YImage>(entity =>
        {
            entity.HasKey(e => e.ImageId).HasName("PK__yImage__7516F70CE266B27C");

            entity.ToTable("yImage");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<YImageRelation>(entity =>
        {
            entity.HasKey(e => e.ImageRelationId).HasName("PK__yImageRe__9051C4D6BCDA8C62");

            entity.ToTable("yImageRelation");

            entity.Property(e => e.ImageUse).HasMaxLength(50);
            entity.Property(e => e.PostType).HasMaxLength(30);

            entity.HasOne(d => d.Image).WithMany(p => p.YImageRelations)
                .HasForeignKey(d => d.ImageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yImageRelation_yImage");
        });

        modelBuilder.Entity<YJoinForm>(entity =>
        {
            entity.HasKey(e => e.JoinFormId).HasName("PK__yJoinFor__704A873963A4CFA0");

            entity.ToTable("yJoinForm");

            entity.Property(e => e.CheckStatus).HasAnnotation("Relational:DefaultConstraintName", "DF_yJoinForm_CheckStatus");
            entity.Property(e => e.CheckTime).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Fee).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Image).HasMaxLength(500);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Event).WithMany(p => p.YJoinForms)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yJoinForm_yPostEvent");

            entity.HasOne(d => d.User).WithMany(p => p.YJoinForms)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_yJoinForm_uUser");
        });

        modelBuilder.Entity<YPost>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__yPost__AA12601857140930");

            entity.ToTable("yPost");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__yPost__CreatedAt__36470DEF")
                .HasColumnType("datetime");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF__yPost__IsDeleted__382F5661");
            entity.Property(e => e.IsPinned).HasAnnotation("Relational:DefaultConstraintName", "DF__yPost__IsPinned__373B3228");
            entity.Property(e => e.Sort).HasAnnotation("Relational:DefaultConstraintName", "DF__yPost__Sort__345EC57D");
            entity.Property(e => e.Status).HasAnnotation("Relational:DefaultConstraintName", "DF_yPost_Status");
            entity.Property(e => e.SubTitle).HasMaxLength(100);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.ViewCount).HasAnnotation("Relational:DefaultConstraintName", "DF__yPost__ViewCount__3552E9B6");

            entity.HasOne(d => d.Coach).WithMany(p => p.YPosts)
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yPost_uCoach");

            entity.HasOne(d => d.ImageRelation).WithMany(p => p.YPosts)
                .HasForeignKey(d => d.ImageRelationId)
                .HasConstraintName("FK_yPost_yImageRelation");

            entity.HasOne(d => d.PostCategory).WithMany(p => p.YPosts)
                .HasForeignKey(d => d.PostCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yPost_yPostCategory");

            entity.HasOne(d => d.TagMapping).WithMany(p => p.YPosts)
                .HasForeignKey(d => d.TagMappingId)
                .HasConstraintName("FK_yPost_yPostTagMapping");
        });

        modelBuilder.Entity<YPostCategory>(entity =>
        {
            entity.HasKey(e => e.PostCategoryId).HasName("PK__yPostCat__FE61E309088AA01D");

            entity.ToTable("yPostCategory");

            entity.Property(e => e.Detail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<YPostEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__yPostEve__AA1260185BEDC09B");

            entity.ToTable("yPostEvent");

            entity.Property(e => e.Detail).HasMaxLength(500);
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.Fee).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Registrationdeadline).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Venue).HasMaxLength(500);

            entity.HasOne(d => d.Post).WithMany(p => p.YPostEvents)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yPostEvent_yPost");
        });

        modelBuilder.Entity<YPostLike>(entity =>
        {
            entity.HasKey(e => e.PostLikeId).HasName("PK__yPostLik__4CF65C1968ECC8A8");

            entity.ToTable("yPostLike");

            entity.HasOne(d => d.Post).WithMany(p => p.YPostLikes)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yPostLike_yPost");
        });

        modelBuilder.Entity<YPostTagMapping>(entity =>
        {
            entity.HasKey(e => e.TagMappingId);

            entity.ToTable("yPostTagMapping");

            entity.HasOne(d => d.Tag).WithMany(p => p.YPostTagMappings)
                .HasForeignKey(d => d.TagId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_yPostTagMapping_yTag");
        });

        modelBuilder.Entity<YQuestionCategory>(entity =>
        {
            entity.HasKey(e => e.QuestionCategoryId).HasName("PK__yQuestio__48FE408103D5AA7F");

            entity.ToTable("yQuestionCategory");

            entity.Property(e => e.Detail)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<YTag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("PK__yTag__657CF9ACE1B7C954");

            entity.ToTable("yTag");

            entity.HasIndex(e => e.TagName, "UQ__yTag__BDE0FD1DDF12E0A5").IsUnique();

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}