// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SCart
{
    public int CartId { get; set; }

    public int SpecId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public int UserId { get; set; }

    public DateTime TimeStamp { get; set; }

    public virtual SSpecification Spec { get; set; }

    public virtual UUser User { get; set; }
}