// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SCategory
{
    public int CId { get; set; }

    public string CName { get; set; }

    public virtual ICollection<SProduct> SProducts { get; set; } = new List<SProduct>();
}