// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SComment
{
    public int ComId { get; set; }

    public int UserId { get; set; }

    public int OdId { get; set; }

    public DateTime CommentTime { get; set; }

    public int CommentStar { get; set; }

    public string Productcomment { get; set; }

    public virtual SOrderDetail Od { get; set; }
}