// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SDiscount
{
    public int DisId { get; set; }

    public string Code { get; set; }

    public string DiscountType { get; set; }

    public decimal Discount { get; set; }

    public bool Activate { get; set; }

    public virtual ICollection<SOrder> SOrders { get; set; } = new List<SOrder>();
}