// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SImage
{
    public int PicId { get; set; }

    public int PId { get; set; }

    public int? SpecId { get; set; }

    public string Picture { get; set; }

    public int? Sort { get; set; }

    public bool MainPicture { get; set; }

    public string ImageType { get; set; }

    public virtual SProduct PIdNavigation { get; set; }

    public virtual SSpecification Spec { get; set; }
}