// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SOrder
{
    public int OId { get; set; }

    public int UserId { get; set; }

    public string MName { get; set; }

    public string MPhone { get; set; }

    public string Email { get; set; }

    public string MAddress { get; set; }

    public DateTime Date { get; set; }

    public string OStatus { get; set; }

    public decimal? ShipFee { get; set; }

    public decimal? HandlingFee { get; set; }

    public decimal Total { get; set; }

    public int PayId { get; set; }

    public string PayStatus { get; set; }

    public int ShipId { get; set; }

    public string Note { get; set; }

    public int? DisId { get; set; }

    public string OrderNumber { get; set; }

    public virtual SDiscount Dis { get; set; }

    public virtual SPayment Pay { get; set; }

    public virtual ICollection<SOrderDetail> SOrderDetails { get; set; } = new List<SOrderDetail>();

    public virtual SShipper Ship { get; set; }

    public virtual UUser User { get; set; }
}