// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SOrderDetail
{
    public int OdId { get; set; }

    public string PName { get; set; }

    public int OId { get; set; }

    public int SpecId { get; set; }

    public decimal SPrice { get; set; }

    public decimal Quantity { get; set; }

    public decimal Subtotal { get; set; }

    public virtual SOrder OIdNavigation { get; set; }

    public virtual ICollection<SComment> SComments { get; set; } = new List<SComment>();

    public virtual SSpecification Spec { get; set; }
}