// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SPayment
{
    public int PayId { get; set; }

    public string Payment { get; set; }

    public decimal? HandlingFee { get; set; }

    public bool Activate { get; set; }

    public virtual ICollection<SOrder> SOrders { get; set; } = new List<SOrder>();
}