// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SProduct
{
    public int PId { get; set; }

    public string PName { get; set; }

    public int SupId { get; set; }

    public int CId { get; set; }

    public string Description { get; set; }

    public virtual SCategory CIdNavigation { get; set; }

    public virtual ICollection<SImage> SImages { get; set; } = new List<SImage>();

    public virtual ICollection<SSpecification> SSpecifications { get; set; } = new List<SSpecification>();

    public virtual SSupplier Sup { get; set; }
}