// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class SSpecification
{
    public int SpecId { get; set; }

    public int PId { get; set; }

    public string SpecName { get; set; }

    public decimal Price { get; set; }

    public decimal? DiscountPrice { get; set; }

    public decimal? InStock { get; set; }

    public bool Release { get; set; }

    public string SpecDetail { get; set; }

    public virtual SProduct PIdNavigation { get; set; }

    public virtual ICollection<SCart> SCarts { get; set; } = new List<SCart>();

    public virtual ICollection<SImage> SImages { get; set; } = new List<SImage>();

    public virtual ICollection<SOrderDetail> SOrderDetails { get; set; } = new List<SOrderDetail>();
}