// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class TMealCategory
{
    public int FCategoryId { get; set; }

    public string FCategoryName { get; set; }

    public string FDescription { get; set; }

    public bool FIsActive { get; set; }

    public virtual ICollection<TMeal> TMeals { get; set; } = new List<TMeal>();
}