// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class TMeal
{
    public int FMealId { get; set; }

    public int FCategoryId { get; set; }

    public string FMealName { get; set; }

    public string FDescription { get; set; }

    public string FImageUrl { get; set; }

    public int FCalories { get; set; }

    public int? FCarbs { get; set; }

    public int FProtein { get; set; }

    public int? FFat { get; set; }

    public int FPrice { get; set; }

    public bool FIsActive { get; set; }

    public virtual TMealCategory FCategory { get; set; }

    public virtual ICollection<TMealEverydayMenu> TMealEverydayMenus { get; set; } = new List<TMealEverydayMenu>();

    public virtual ICollection<TMealFavoriteMeal> TMealFavoriteMeals { get; set; } = new List<TMealFavoriteMeal>();

    public virtual ICollection<TMealOrderItem> TMealOrderItems { get; set; } = new List<TMealOrderItem>();
}