// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class TMealEverydayMenu
{
    public int FEverydayMenuId { get; set; }

    public int FMealId { get; set; }

    public DateOnly FMenuDate { get; set; }

    public bool FIsActive { get; set; }

    public virtual TMeal FMeal { get; set; }
}