// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class TMealFavoriteMeal
{
    public int FFavoriteMealId { get; set; }

    public int FUserId { get; set; }

    public int FMealId { get; set; }

    public DateTime FCreatedAt { get; set; }

    public virtual TMeal FMeal { get; set; }

    public virtual UUser FUser { get; set; }
}