// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class TMealPickUpTime
{
    public int FPickUpTimeId { get; set; }

    public TimeOnly FStartTime { get; set; }

    public TimeOnly FEndTime { get; set; }

    public bool FIsActive { get; set; }

    public virtual ICollection<TMealOrderItem> TMealOrderItems { get; set; } = new List<TMealOrderItem>();
}