// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class TMealOrderItem
{
    public int FOrderItemId { get; set; }

    public int FOrderId { get; set; }

    public int FMealId { get; set; }

    public int FQty { get; set; }

    public int FUnitPrice { get; set; }

    public int FSubtotal { get; set; }

    public int FPickTimeId { get; set; }

    public DateOnly FPickDate { get; set; }

    public string FQrContent { get; set; }

    public bool FPickupStatus { get; set; }

    public virtual TMeal FMeal { get; set; }

    public virtual TMealOrder FOrder { get; set; }

    public virtual TMealPickUpTime FPickTime { get; set; }
}