// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class TMealOrder
{
    public int FOrderId { get; set; }

    public int? FUserId { get; set; }

    public string FOrderName { get; set; }

    public string FOrderPhone { get; set; }

    public string FOrderEmail { get; set; }

    public DateTime FCartCreateAt { get; set; }

    public DateTime? FOrderAt { get; set; }

    public int? FVenueId { get; set; }

    public int? FTotalAmount { get; set; }

    public string FOrderStatus { get; set; }

    public string FPayMethod { get; set; }

    public virtual UUser FUser { get; set; }

    public virtual CVenue FVenue { get; set; }

    public virtual ICollection<TMealOrderItem> TMealOrderItems { get; set; } = new List<TMealOrderItem>();
}