// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UCoach
{
    public int CoachId { get; set; }

    public string Name { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public int Sex { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public int VenueId { get; set; }

    public byte[] Image { get; set; }

    public byte Status { get; set; }

    public bool IsManager { get; set; }

    public string Descrition { get; set; }

    public decimal HourlyRate { get; set; }

    public virtual ICollection<CCoachSchedule> CCoachSchedules { get; set; } = new List<CCoachSchedule>();

    public virtual ICollection<UCoachSkill> UCoachSkills { get; set; } = new List<UCoachSkill>();

    public virtual ICollection<UCouchDeactivateLog> UCouchDeactivateLogs { get; set; } = new List<UCouchDeactivateLog>();

    public virtual CVenue Venue { get; set; }

    public virtual ICollection<YCustomerService> YCustomerServices { get; set; } = new List<YCustomerService>();

    public virtual ICollection<YPost> YPosts { get; set; } = new List<YPost>();
}