// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UCoachSkill
{
    public int CoachSkillId { get; set; }

    public int CoachId { get; set; }

    public string SkillName { get; set; }

    public string SkillInfo { get; set; }

    public virtual UCoach Coach { get; set; }
}