// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UCouchDeactivateLog
{
    public int LogId { get; set; }

    public int CoachId { get; set; }

    public byte DeactivateType { get; set; }

    public DateTime DeactivateStartTime { get; set; }

    public DateTime DeactivateEndTime { get; set; }

    public string Reason { get; set; }

    public virtual UCoach Coach { get; set; }
}