// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UDairyDetail
{
    public int DetailId { get; set; }

    public int DairyId { get; set; }

    public int FoodId { get; set; }

    public int MealType { get; set; }

    public decimal Qty { get; set; }

    public decimal Kcal { get; set; }

    public virtual UDairy Dairy { get; set; }

    public virtual UFood Food { get; set; }
}