// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UDairy
{
    public int DairyId { get; set; }

    public int UserId { get; set; }

    public DateOnly Date { get; set; }

    public string Description { get; set; }

    public virtual ICollection<UDairyDetail> UDairyDetails { get; set; } = new List<UDairyDetail>();

    public virtual UUser User { get; set; }
}