// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UDietType
{
    public int DietTypeId { get; set; }

    public string DietName { get; set; }

    public int? UserId { get; set; }

    public int CarbPercent { get; set; }

    public int ProteinPercent { get; set; }

    public int FatPercent { get; set; }

    public bool IsSystem { get; set; }

    public virtual UUser User { get; set; }
}