// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UExerciseType
{
    public int ExerciseTypeId { get; set; }

    public string TypeName { get; set; }

    public bool IsActive { get; set; }

    public int SortOrder { get; set; }

    public virtual ICollection<UExerciseItem> UExerciseItems { get; set; } = new List<UExerciseItem>();
}