// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UExerciseItem
{
    public int ItemId { get; set; }

    public int? UserId { get; set; }

    public string ExerciseName { get; set; }

    public int ExerciseTypeId { get; set; }

    public bool IsSystem { get; set; }

    public bool IsActive { get; set; }

    public virtual UExerciseType ExerciseType { get; set; }

    public virtual ICollection<UExerciseRecord> UExerciseRecords { get; set; } = new List<UExerciseRecord>();
}