// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UExerciseRecord
{
    public int ExerciseId { get; set; }

    public int UserId { get; set; }

    public int ItemId { get; set; }

    public DateTime StartTime { get; set; }

    public decimal? Duration { get; set; }

    public int? Machine { get; set; }

    public decimal? Met { get; set; }

    public int? Sets { get; set; }

    public int? Reps { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Kcal { get; set; }

    public virtual UExerciseItem Item { get; set; }

    public virtual UUser User { get; set; }
}