// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UFood
{
    public int FoodId { get; set; }

    public int CategoryId { get; set; }

    public string FoodName { get; set; }

    public decimal PortionSize { get; set; }

    public decimal Kcal { get; set; }

    public decimal Cho { get; set; }

    public decimal Protein { get; set; }

    public decimal Fat { get; set; }

    public string Text { get; set; }

    public byte[] FoodImage { get; set; }

    public virtual UFoodCategory Category { get; set; }

    public virtual ICollection<UDairyDetail> UDairyDetails { get; set; } = new List<UDairyDetail>();
}