// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UUserWeightRecord
{
    public int RecordId { get; set; }

    public int UserId { get; set; }

    public DateOnly RecordDate { get; set; }

    public decimal Weight { get; set; }

    public DateTime CreatedAt { get; set; }

    public decimal? BodyFat { get; set; }

    public decimal? MuscleMass { get; set; }

    public virtual UUser User { get; set; }
}