// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class UUser
{
    public int UserId { get; set; }

    public string Name { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Sex { get; set; }

    public DateOnly BirthDate { get; set; }

    public string Phone { get; set; }

    public byte Status { get; set; }

    public string Address { get; set; }

    public DateTime CreatedDate { get; set; }

    public byte[] Image { get; set; }

    public string Email { get; set; }

    public bool IsEmailVerified { get; set; }

    public byte[] PasswordSalt { get; set; }

    public string LoginProvider { get; set; }

    public DateTime? EmailVerifiedAt { get; set; }

    public string LineId { get; set; }

    public string GoogleId { get; set; }

    public virtual ICollection<CCoachBooking> CCoachBookings { get; set; } = new List<CCoachBooking>();

    public virtual ICollection<CCourseBooking> CCourseBookings { get; set; } = new List<CCourseBooking>();

    public virtual ICollection<CReview> CReviews { get; set; } = new List<CReview>();

    public virtual ICollection<SCart> SCarts { get; set; } = new List<SCart>();

    public virtual ICollection<SOrder> SOrders { get; set; } = new List<SOrder>();

    public virtual ICollection<TMealFavoriteMeal> TMealFavoriteMeals { get; set; } = new List<TMealFavoriteMeal>();

    public virtual ICollection<TMealOrder> TMealOrders { get; set; } = new List<TMealOrder>();

    public virtual ICollection<UDairy> UDairies { get; set; } = new List<UDairy>();

    public virtual ICollection<UDietType> UDietTypes { get; set; } = new List<UDietType>();

    public virtual ICollection<UExerciseRecord> UExerciseRecords { get; set; } = new List<UExerciseRecord>();

    public virtual ICollection<UUserDeactivateLog> UUserDeactivateLogs { get; set; } = new List<UUserDeactivateLog>();

    public virtual ICollection<UUserHealthProfile> UUserHealthProfiles { get; set; } = new List<UUserHealthProfile>();

    public virtual ICollection<UUserWeightRecord> UUserWeightRecords { get; set; } = new List<UUserWeightRecord>();

    public virtual ICollection<YCustomerService> YCustomerServices { get; set; } = new List<YCustomerService>();

    public virtual ICollection<YJoinForm> YJoinForms { get; set; } = new List<YJoinForm>();
}