// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YCustomerService
{
    public int CustomerServiceId { get; set; }

    public int QuestionCategoryId { get; set; }

    public int? UserId { get; set; }

    public int? CoachId { get; set; }

    public byte[] Image { get; set; }

    public string Name { get; set; }

    public int Sex { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Detail { get; set; }

    public string ReplyContent { get; set; }

    public int Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? RepliedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual UCoach Coach { get; set; }

    public virtual YQuestionCategory QuestionCategory { get; set; }

    public virtual UUser User { get; set; }
}