// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YFaq
{
    public int FaqId { get; set; }

    public int QuestionCategoryId { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual YQuestionCategory QuestionCategory { get; set; }
}