// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YImage
{
    public int ImageId { get; set; }

    public int ImageType { get; set; }

    public string ImageUrl { get; set; }

    public string AltText { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<YImageRelation> YImageRelations { get; set; } = new List<YImageRelation>();
}