// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YImageRelation
{
    public int ImageRelationId { get; set; }

    public int ImageId { get; set; }

    public int PostId { get; set; }

    public string PostType { get; set; }

    public string ImageUse { get; set; }

    public virtual YImage Image { get; set; }

    public virtual ICollection<YPost> YPosts { get; set; } = new List<YPost>();
}