// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YJoinForm
{
    public int JoinFormId { get; set; }

    public int EventId { get; set; }

    public int? UserId { get; set; }

    public string Name { get; set; }

    public int Sex { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public int Status { get; set; }

    public int PayStatus { get; set; }

    public int PayMethod { get; set; }

    public decimal Fee { get; set; }

    public int CheckStatus { get; set; }

    public string Image { get; set; }

    public DateTime? CheckTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual YPostEvent Event { get; set; }

    public virtual UUser User { get; set; }
}