// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YPostEvent
{
    public int EventId { get; set; }

    public int PostId { get; set; }

    public decimal? Fee { get; set; }

    public string Detail { get; set; }

    public string Venue { get; set; }

    public int? Status { get; set; }

    public int MaxPeople { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public DateTime? Registrationdeadline { get; set; }

    public virtual YPost Post { get; set; }

    public virtual ICollection<YJoinForm> YJoinForms { get; set; } = new List<YJoinForm>();
}