// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YPostCategory
{
    public int PostCategoryId { get; set; }

    public int PostType { get; set; }

    public string Name { get; set; }

    public string Detail { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<YPost> YPosts { get; set; } = new List<YPost>();
}