// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YPost
{
    public int PostId { get; set; }

    public int CoachId { get; set; }

    public int PostCategoryId { get; set; }

    public int? ImageRelationId { get; set; }

    public int? TagMappingId { get; set; }

    public string Title { get; set; }

    public string SubTitle { get; set; }

    public string Detail { get; set; }

    public int Sort { get; set; }

    public int ViewCount { get; set; }

    public int Status { get; set; }

    public DateOnly? PostedDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int IsPinned { get; set; }

    public bool IsDeleted { get; set; }

    public virtual UCoach Coach { get; set; }

    public virtual YImageRelation ImageRelation { get; set; }

    public virtual YPostCategory PostCategory { get; set; }

    public virtual YPostTagMapping TagMapping { get; set; }

    public virtual ICollection<YPostEvent> YPostEvents { get; set; } = new List<YPostEvent>();

    public virtual ICollection<YPostLike> YPostLikes { get; set; } = new List<YPostLike>();
}