// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YPostLike
{
    public int PostLikeId { get; set; }

    public int PostId { get; set; }

    public int UserId { get; set; }

    public virtual YPost Post { get; set; }
}