// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YPostTagMapping
{
    public int TagMappingId { get; set; }

    public int TagId { get; set; }

    public virtual YTag Tag { get; set; }

    public virtual ICollection<YPost> YPosts { get; set; } = new List<YPost>();
}