// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YQuestionCategory
{
    public int QuestionCategoryId { get; set; }

    public string Name { get; set; }

    public string Detail { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<YCustomerService> YCustomerServices { get; set; } = new List<YCustomerService>();

    public virtual ICollection<YFaq> YFaqs { get; set; } = new List<YFaq>();
}