// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gym_api.Models;

public partial class YTag
{
    public int TagId { get; set; }

    public string TagName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<YPostTagMapping> YPostTagMappings { get; set; } = new List<YPostTagMapping>();
}